latest_posts: Últimos Posts
read_more: Leer Más
powered_by: Powered by
prev: Prev
next: Sig.
archive: Archive
about_this_post: Sobre este Post
this_post_is_written_by: Escrito por
licensed_under: licenciado bajo
home: Home
January: Enero
February: Febrero
March: Marzo
April: Abril
May: Mayo
June: Junio
July: Julio
August: Agosto
September: Septiembre
October: Octubre
November: Noviembre
December: Deciembre
